// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://zuxmjyndgwdkhtdqmehz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1eG1qeW5kZ3dka2h0ZHFtZWh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0Nzc2ODcsImV4cCI6MjA2NjA1MzY4N30.03xUBBX75DV9p1uNbj-0uZjxtbCBu_6_c0xjjvezpn4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);